version: '3.9'

services:
  # Flask service
  backend:
    container_name: backend
    build:
      context: ./backend-flask
      #image: jazzdd/alpine-flask:python3
    ports:
      - ":5000"
    volumes:
      - ./backend-flask:/app
    networks:
      - dev-network

  # Vue + Vite service
  frontend:
    container_name: frontend
    build:
      context: ./availabili.tf
    ports:
      - ":5173"
    environment:
      VITE_API_URL: http://localhost:8000  # API endpoint
    volumes:
      - ./availabili.tf:/app
    networks:
      - dev-network

  # NGINX service
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
