services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - ./sqlite3:/app/sqlite3
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    environment:
      - DB_URI=sqlite:///./sqlite3/db.sqlite3
